#!/bin/bash

# Hank Project Setup Script
# Creates project structure with Hank-specific files in .hank/ subfolder
set -e

PROJECT_NAME=${1:-"my-project"}

echo "🚀 Setting up Hank project: $PROJECT_NAME"

# Create project directory
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

# Determine templates directory location (checked AFTER cd into project)
# Check local ../templates first, then global ~/.hank/templates
TEMPLATES_DIR=""
LIB_DIR=""
if [[ -d "../templates" ]]; then
    TEMPLATES_DIR="../templates"
    LIB_DIR="../lib"
elif [[ -d "$HOME/.hank/templates" ]]; then
    TEMPLATES_DIR="$HOME/.hank/templates"
    LIB_DIR="$HOME/.hank/lib"
else
    echo "❌ Error: Templates directory not found."
    echo "   Expected at: ../templates or ~/.hank/templates"
    echo "   Please run ./install.sh first to install Hank globally."
    exit 1
fi

# Verify required template files exist
if [[ ! -f "$TEMPLATES_DIR/PROMPT.md" ]]; then
    echo "❌ Error: Required template file PROMPT.md not found in $TEMPLATES_DIR"
    exit 1
fi

# Create structure:
# - src/ stays at root for compatibility with existing tooling
# - All Hank-specific files go in .hank/ subfolder
mkdir -p src
mkdir -p .hank/{specs/stdlib,examples,logs,docs/generated}

# Copy templates to .hank/
cp "$TEMPLATES_DIR/PROMPT.md" .hank/
cp "$TEMPLATES_DIR/fix_plan.md" .hank/fix_plan.md
cp "$TEMPLATES_DIR/AGENT.md" .hank/AGENT.md
cp -r "$TEMPLATES_DIR/specs"/* .hank/specs/ 2>/dev/null || true

# Generate .hankrc configuration file
# Source enable_core.sh if available for generate_hankrc(), otherwise create inline
if [[ -f "$LIB_DIR/enable_core.sh" ]]; then
    # Temporarily disable colors for cleaner output
    export ENABLE_USE_COLORS=false
    source "$LIB_DIR/enable_core.sh"
    # Generate .hankrc and fix the generator label (library says "hank enable")
    generate_hankrc "$PROJECT_NAME" "generic" "local" | sed 's/Generated by: hank enable/Generated by: hank-setup/' > .hankrc
else
    # Fallback: create minimal .hankrc inline (same content as generate_hankrc)
    cat > .hankrc << HANKRCEOF
# .hankrc - Hank project configuration
# Generated by: hank-setup
# Documentation: https://github.com/jacklenzotti/hank

# Project identification
PROJECT_NAME="${PROJECT_NAME}"
PROJECT_TYPE="generic"

# Loop settings
MAX_CALLS_PER_HOUR=100
CLAUDE_TIMEOUT_MINUTES=15
CLAUDE_OUTPUT_FORMAT="json"

# Tool permissions
# Comma-separated list of allowed tools
ALLOWED_TOOLS="Write,Read,Edit,Bash(git *),Bash(npm *),Bash(pytest)"

# Session management
SESSION_CONTINUITY=true
SESSION_EXPIRY_HOURS=24

# Task sources (for hank enable --sync)
# Options: local, beads, github (comma-separated for multiple)
TASK_SOURCES="local"
GITHUB_TASK_LABEL="hank-task"
BEADS_FILTER="status:open"

# Circuit breaker thresholds
CB_NO_PROGRESS_THRESHOLD=3
CB_SAME_ERROR_THRESHOLD=5
CB_OUTPUT_DECLINE_THRESHOLD=70
HANKRCEOF
fi

# Initialize git (skip if already initialized)
if [[ ! -d ".git" ]]; then
    git init
fi
echo "# $PROJECT_NAME" > README.md
git add .
git commit -m "Initial Hank project setup"

echo "✅ Project $PROJECT_NAME created!"
echo "Next steps:"
echo "  1. Edit .hank/PROMPT.md with your project requirements"
echo "  2. Update .hank/specs/ with your project specifications"
echo "  3. Run: ../hank_loop.sh"
echo "  4. Monitor: ../hank_monitor.sh"
